using System.ComponentModel.DataAnnotations;
using TodoApi.Constants;

namespace TodoApi.Models;

/// <summary>
/// Represents a single todo task in the system
/// </summary>
public class TodoTask
{
    /// <summary>
    /// Unique identifier — auto generated by the database
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Title of the task — required, max 200 characters
    /// </summary>
    [Required(ErrorMessage = ErrorMessages.TaskTitleRequired)]
    [MaxLength(200, ErrorMessage = ErrorMessages.TaskTitleTooLong)]
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Optional detailed description — max 1000 characters
    /// </summary>
    [MaxLength(1000, ErrorMessage = ErrorMessages.TaskDescriptionTooLong)]
    public string? Description { get; set; }

    /// <summary>
    /// Whether the task has been completed — defaults to false
    /// </summary>
    public bool IsCompleted { get; set; } = false;

    /// <summary>
    /// Priority level — must be Low, Medium or High — defaults to Medium
    /// </summary>
    [RegularExpression("Low|Medium|High",
        ErrorMessage = ErrorMessages.TaskPriorityInvalid)]
    public string Priority { get; set; } = "Medium";

    /// <summary>
    /// Timestamp when task was created — always set server side
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Optional date the task is due
    /// </summary>
    public DateTime? DueDate { get; set; }

    /// <summary>
    /// Optional reminder date and time
    /// </summary>
    public DateTime? ReminderAt { get; set; }

    /// <summary>
    /// Email of the user who created the task — must be valid email format
    /// </summary>
    [EmailAddress(ErrorMessage = ErrorMessages.EmailInvalid)]
    public string? CreatedByEmail { get; set; }

    /// <summary>
    /// Email of the user this task is delegated to — must be valid email format
    /// </summary>
    [EmailAddress(ErrorMessage = ErrorMessages.EmailInvalid)]
    public string? AssignedToEmail { get; set; }
}